# Generated by Django 3.0.7 on 2020-07-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lampe', 'Lampe'), ('Prise', 'Prise'), ('Rideau', 'Rideau')], max_length=255)),
                ('etat', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='chambres.Chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('commande', models.CharField(max_length=255)),
                ('device', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='chambres.Device')),
            ],
        ),
    ]
