# Generated by Django 3.0.7 on 2020-09-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalenge', models.CharField(max_length=300)),
                ('result', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=300)),
                ('heure', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
