# Generated by Django 3.0.7 on 2020-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('identifiant', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('cle_local', models.CharField(max_length=255)),
            ],
        ),
    ]
